// Registry of the drawing parts of the empire mechanics. Each empire's file exports `render` when it has something to draw.
import type { MechRenderRegistry } from './types';
export type { MechRender } from './types';

import { render as aboriginal } from './aboriginal';
import { render as aztec } from './aztec';
import { render as celts } from './celts';
import { render as china } from './china';
import { render as egypt } from './egypt';
import { render as ethiopia } from './ethiopia';
import { render as greeks } from './greeks';
import { render as inca } from './inca';
import { render as inuit } from './inuit';
import { render as japan } from './japan';
import { render as khmer } from './khmer';
import { render as korea } from './korea';
import { render as lakota } from './lakota';
import { render as mali } from './mali';
import { render as maya } from './maya';
import { render as mongols } from './mongols';
import { render as ottoman } from './ottoman';
import { render as persia } from './persia';
import { render as pirates } from './pirates';
import { render as polynesia } from './polynesia';
import { render as rome } from './rome';
import { render as swahili } from './swahili';
import { render as tibet } from './tibet';
import { render as carthage } from './carthage';
import { render as byzantium } from './byzantium';
import { render as arabia } from './arabia';
import { render as rus } from './rus';
import { render as vietnam } from './vietnam';
import { render as babylon } from './babylon';
import { render as nubia } from './nubia';
import { render as majapahit } from './majapahit';
import { render as spain } from './spain';
import { render as haudenosaunee } from './haudenosaunee';
import { render as assyria } from './assyria';
import { render as poland } from './poland';
import { render as scotland } from './scotland';
import { render as england } from './england';
import { render as france } from './france';
import { render as germany } from './germany';
import { render as sweden } from './sweden';
import { render as portugal } from './portugal';
import { render as venice } from './venice';
import { render as kongo } from './kongo';
import { render as ashanti } from './ashanti';
import { render as mapuche } from './mapuche';
import { render as georgia } from './georgia';
import { render as nepal } from './nepal';
import { render as cree } from './cree';
import { render as vikings } from './vikings';
import { render as zulu } from './zulu';

export const MECH_RENDER: MechRenderRegistry = { aboriginal, aztec, celts, china, egypt, ethiopia, greeks, inca, inuit, japan, khmer, korea, lakota, mali, maya, mongols, ottoman, persia, pirates, polynesia, rome, swahili, tibet, vikings, zulu, carthage, byzantium, arabia, rus, vietnam, babylon, nubia, majapahit, spain, haudenosaunee, assyria, poland, scotland, england, france, germany, sweden, portugal, venice, kongo, ashanti, mapuche, georgia, nepal, cree };
