/* ============================================================
   Cloud snapshot — the read-only fallback used when there is no
   Express server to talk to (the Vercel deploy has no backend at
   all; a Mac that's asleep has none reachable either).

   Generated by scripts/sync-cloud.mjs into cloud-data/snapshot.json,
   committed to git, and served as a static file. Fetched once and
   cached for the life of the tab.

   The fetch path below is deliberately relative (no leading slash) — this
   app is deployed at different roots depending on where it's running
   (Vercel's domain root, GitHub Pages' /trading-dashboard/ subpath, the
   Mac's /trading/ mount under Express), and a relative path resolves
   against whichever one is current instead of assuming root.
   ============================================================ */

import type { Entry, DisciplineData } from '../types';
import type { VaultFolder, VaultNote, VaultNoteRef } from './api';

export type CloudSnapshot = {
  syncedAt: string;
  trades: { entries: Entry[] };
  discipline: DisciplineData;
  vault: {
    vault: string;
    noteCount: number;
    tree: VaultFolder;
    notes: Record<string, VaultNote>;
    backlinksByPath: Record<string, VaultNoteRef[]>;
    mediaMap: Record<string, string>;
  };
};

let cached: CloudSnapshot | null | undefined; // undefined = not fetched yet
let inFlight: Promise<CloudSnapshot | null> | null = null;

/** Fetches once, caches the result (including a definitive "no snapshot here"). */
export function loadCloudSnapshot(): Promise<CloudSnapshot | null> {
  if (cached !== undefined) return Promise.resolve(cached);
  if (inFlight) return inFlight;
  inFlight = fetch('cloud-data/snapshot.json')
    .then((res) => (res.ok ? res.json() : null))
    .catch(() => null)
    .then((data: CloudSnapshot | null) => {
      cached = data;
      inFlight = null;
      return data;
    });
  return inFlight;
}

/** Synchronous read of whatever loadCloudSnapshot last resolved, if anything. */
export function cachedCloudSnapshot(): CloudSnapshot | null {
  return cached ?? null;
}
