/* ============================================================
   Installs Mission Control as a launchd agent, generating the plist from
   wherever this checkout actually lives.

   The plist this replaces was a checked-in file with three facts frozen into
   it: /Users/niko/Desktop/Claude/TD v1 as the working directory, and
   /usr/local/bin/node as the interpreter. Both are guesses that only hold on
   one machine in one state. /usr/local/bin/node is the Intel Homebrew path —
   on Apple Silicon node lives at /opt/homebrew/bin/node, and under nvm it is
   somewhere else again. A wrong interpreter does not fail loudly: launchd
   execs it, gets ENOENT, and KeepAlive dutifully retries forever, so the
   symptom is a dashboard that is simply never up, with nothing obviously
   broken to look at.

   Generating the plist removes the guesses. The working directory is this
   file's own repo root, and the interpreter is process.execPath — the exact
   node binary running this script, which is by construction one that works.

   The other frozen bug was ordering. StandardOutPath pointed into data/, but
   data/ is gitignored, so on a fresh clone it does not exist yet — and launchd
   opens those log paths *before* exec'ing the program, so it could not create
   them. The server's own ensureDataDirs() runs too late to help: it is inside
   the process launchd is still trying to start. This creates data/ first.
   ============================================================ */

import { execFile } from 'node:child_process';
import { access, mkdir, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { promisify } from 'node:util';
import { fileURLToPath } from 'node:url';
import {
  DATA_DIR,
  ERROR_LOG_FILE,
  LOG_FILE,
  PORT,
  ROOT,
} from '../server/config.mjs';

const run = promisify(execFile);

const LABEL = 'com.niko.missioncontrol';
const PLIST_PATH = path.join(os.homedir(), 'Library', 'LaunchAgents', `${LABEL}.plist`);
const TARGET = `gui/${process.getuid()}`;

function xml(value) {
  return String(value).replace(
    /[&<>]/g,
    (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' })[c],
  );
}

/** launchd inherits nothing from your shell, so anything the server reads from
 *  the environment has to be written into the plist explicitly. VAULT_ROOT is
 *  only carried over when it is actually set here — otherwise config.mjs's
 *  iCloud default is the better answer, and baking the default in would freeze
 *  a path that config.mjs is free to change later. */
function environmentBlock() {
  const vars = { NODE_ENV: 'production', PORT: String(PORT) };
  if (process.env.VAULT_ROOT) vars.VAULT_ROOT = process.env.VAULT_ROOT;
  return Object.entries(vars)
    .map(([k, v]) => `        <key>${xml(k)}</key>\n        <string>${xml(v)}</string>`)
    .join('\n');
}

/** Exported so the generated XML can be checked without a Mac to load it on.
 *  A malformed plist is the worst failure this script has: launchctl rejects
 *  it, and the agent that never starts looks identical to one that crashed. */
export function buildPlist() {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- generated by scripts/install-agent.mjs — re-run it rather than editing this -->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${xml(LABEL)}</string>

    <key>ProgramArguments</key>
    <array>
        <string>${xml(process.execPath)}</string>
        <string>${xml(path.join(ROOT, 'server', 'index.mjs'))}</string>
    </array>

    <key>WorkingDirectory</key>
    <string>${xml(ROOT)}</string>

    <key>EnvironmentVariables</key>
    <dict>
${environmentBlock()}
    </dict>

    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>

    <!-- If the server dies on startup — a bad build, a port already taken —
         KeepAlive turns that into a restart loop. Ten seconds between attempts
         keeps a loop from pinning a core while you work out what is wrong. -->
    <key>ThrottleInterval</key>
    <integer>10</integer>

    <key>StandardOutPath</key>
    <string>${xml(LOG_FILE)}</string>
    <key>StandardErrorPath</key>
    <string>${xml(ERROR_LOG_FILE)}</string>
</dict>
</plist>
`;
}

async function exists(p) {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

/** bootout is how you stop an already-installed agent, and it fails when
 *  nothing is loaded — which is the normal case on a first install, not an
 *  error worth reporting. */
async function quiet(args) {
  try {
    await run('launchctl', args);
    return true;
  } catch {
    return false;
  }
}

/** The agent starts the server, it does not build the web app. web/dist is
 *  gitignored, so a fresh clone has no dashboard to serve and /trading would
 *  404 while the hub at / looked perfectly healthy — worth catching here
 *  rather than on the phone. */
async function warnIfUnbuilt() {
  if (!(await exists(path.join(ROOT, 'web', 'dist', 'index.html')))) {
    console.warn('[agent] web/dist is missing — run `npm run build`, or /trading will 404.');
  }
}

function warnIfFragileNode() {
  if (process.execPath.includes('/.nvm/')) {
    console.warn(
      `[agent] node is an nvm build (${process.execPath}).\n` +
        '        The agent pins this exact path — removing that node version breaks it.\n' +
        '        Re-run this installer after any nvm upgrade.',
    );
  }
}

/** Poll rather than sleep once: the first boot has to create data dirs and
 *  stat the vault over iCloud, which is not instant on a cold cache. */
async function waitForHealth() {
  for (let i = 0; i < 20; i++) {
    try {
      const resp = await fetch(`http://127.0.0.1:${PORT}/api/health`);
      if (resp.ok) return await resp.json();
    } catch {
      /* not up yet */
    }
    await new Promise((r) => setTimeout(r, 500));
  }
  return null;
}

async function install() {
  if (process.platform !== 'darwin') {
    console.error('[agent] launchd is macOS-only — nothing to install here.');
    process.exit(1);
  }

  await mkdir(DATA_DIR, { recursive: true });
  await mkdir(path.dirname(PLIST_PATH), { recursive: true });
  await writeFile(PLIST_PATH, buildPlist(), 'utf8');
  console.log(`[agent] wrote ${PLIST_PATH}`);

  warnIfFragileNode();
  await warnIfUnbuilt();

  // Replace whatever is loaded. bootstrap on an already-loaded label is an
  // error, so the bootout has to come first even on a reinstall.
  await quiet(['bootout', `${TARGET}/${LABEL}`]);
  try {
    await run('launchctl', ['bootstrap', TARGET, PLIST_PATH]);
  } catch (err) {
    console.error(`[agent] launchctl bootstrap failed: ${err.stderr || err.message}`);
    process.exit(1);
  }
  await quiet(['enable', `${TARGET}/${LABEL}`]);

  const health = await waitForHealth();
  if (!health) {
    console.error(
      `[agent] loaded, but nothing answered on port ${PORT} within 10s.\n` +
        `        Check ${ERROR_LOG_FILE}`,
    );
    process.exit(1);
  }

  console.log(`[agent] up on port ${PORT} — starts at login, restarts if it dies`);
  if (!health.vault) {
    console.warn(`[agent] vault not found at ${health.vaultRoot} — Knowledge Base will be empty.`);
  }
}

// Importing this file — to check buildPlist without a Mac — must not install.
if (process.argv[1] === fileURLToPath(import.meta.url)) await install();
